version: "3.9"
services:
  api:
    build: ./api
    ports:
      - 3000:3000 
    environment:
      - DB_URL=${DB_URL}

  mongodb:
    image: mongo:latest  
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
