services:
  api:
    build: ./api
    ports:
      - 3000:3000 
    environment:
      - DB_URL=mongodb://admin:password@mongodb  

  mongodb:
    image: mongo:latest  
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
